apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ZG9ja2Vy #docker
  POSTGRES_PASSWORD: ZG9ja2Vy #docker
  POSTGRES_DB:  bW9iaWxpdHlkYg== #moving-object-db

#Always encode the secret parameters with>>>> echo -n your-parameter-value | base64